extends: "@woksin"

plugins:
  - "header"

rules:
  header/header: [2, "line", [" Copyright (c) woksin-org. All rights reserved.", " Licensed under the MIT license. See LICENSE file in the project root for full license information."], 1]
