name: DotNET - IoC - Release

on:
  pull_request:
    types: [closed]
    paths: 
      - Packages/DotNET/IoC/**
      - .github/workflows/dotnet-ioc-*

jobs:
  release:
    permissions: 
      contents: write
    uses: ./.github/workflows/dotnet-reusable-release.yml
    with:
      working-directory: Packages/DotNET/IoC
      library-name: Woksin.Extensions.IoC
    secrets: inherit
