name: .NET Library CI/CD

env:
  PRERELEASE_BRANCHES: alpha,beta,rc
  NUGET_OUTPUT: Artifacts/NuGet

on:
  push:
    branches:
      - "**"
  pull_request:
    types: [closed]

jobs:
  ci:
    name: CI/CD
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup .Net
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x
      - name: Establish context
        id: context
        uses: dolittle/establish-context-action@v2
        with:
          prerelease-branches: ${{ env.PRERELEASE_BRANCHES }}
      - name: Increment version
        id: increment-version
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/increment-version-action@v2
        with:
          version: ${{ steps.context.outputs.current-version }}
          release-type: ${{ steps.context.outputs.release-type }}
      - name: Build
        run: dotnet build --configuration Release
      - name: Test
        run: dotnet test --configuration Release --no-build
      - name: Create release notes
        id: create-release-notes
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        uses: dolittle/create-release-notes-action@v1
        with:
          body: ${{ steps.context.outputs.pr-body }}
          version: ${{ steps.increment-version.outputs.next-version }}
          changelog-url: https://github.com/woksin/IoCExtensions/blob/main/CHANGELOG.md
          output-format: msbuild
      - name: Create packages
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        run: |
          dotnet pack \
            --configuration Release \
            -o ${{ env.NUGET_OUTPUT }} \
            -p:Version=${{ steps.increment-version.outputs.next-version }} \
            -p:PackageVersion=${{ steps.increment-version.outputs.next-version }} \
            -p:PackageReleaseNotes="${{ steps.create-release-notes.outputs.plaintext }}"

      - name: Prepend to Changelog
        if: ${{ steps.context.outputs.should-publish == 'true' && steps.context.outputs.release-type != 'prerelease' }}
        uses: dolittle/add-to-changelog-action@v2
        with:
          version: ${{ steps.increment-version.outputs.next-version }}
          body: ${{ steps.context.outputs.pr-body }}
          pr-url: ${{ steps.context.outputs.pr-url }}
          changelog-path: CHANGELOG.md
          user-email: sindrewilting@gmail.com
          user-name: woksin

      - name: Create GitHub Release
        uses: dolittle/github-release-action@v2
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.increment-version.outputs.next-version }}
          body: ${{ steps.context.outputs.pr-body }}

      - name: Push NuGet packages
        if: ${{ steps.context.outputs.should-publish == 'true' }}
        run: |
          dotnet nuget push \
            --skip-duplicate '${{ env.NUGET_OUTPUT }}/*.nupkg' \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json
